### ISSUE TITLE
mobx-react warnings from TaskNode

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/react-topology#73]
**Describe the problem**
TaskNode is throwing console warnings due to updating data in a non-action wrapped function.

**How do you reproduce the problem?**
Create a pipeline topology graph and use the TaskNode component for displaying nodes.

**Expected behavior**
No warnings are caused

**Is this issue blocking you?**
No

**Screenshots**
```[MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: BaseEdge@24.data 
    at observerComponent (https://prod.foo.redhat.com:1337/beta/api/plugins/hac-dev/js/vendors-node_modules_patternfly_react-core_dist_esm_components_Label_Label_js-node_modules_pa-a7f7eb.js:42410:73)
    at TaskNode (https://prod.foo.redhat.com:1337/beta/api/plugins/hac-dev/js/vendors-node_modules_patternfly_react-core_dist_esm_components_Label_Label_js-node_modules_pa-a7f7eb.js:14132:11)
```

**Comment by jessiehuff** [comment]
https://github.com/patternfly/react-topology/pull/74
